# Generated by Django 2.2.28 on 2022-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='ddww',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
