# Generated by Django 2.2.28 on 2022-05-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pet_ddww'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='asdf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
