# Generated by Django 2.2.26 on 2022-05-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220526_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newnew',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
