# Generated by Django 2.2.26 on 2022-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_newnew"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ddff",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
