# Generated by Django 2.2.26 on 2022-05-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_ddff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="ddff",
            new_name="wwee",
        ),
    ]
