# Generated by Django 2.2.26 on 2022-05-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20220526_1550"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="wwee",
        ),
    ]
