# Generated by Django 2.2.26 on 2022-05-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_wwee"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rree",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wwee",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
