# Generated by Django 2.2.28 on 2022-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20220526_1601"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ffwwee",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
